version: "3.9"

services:
  db:
    image: mysql:5.7
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-schema:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_USER=flaskapp
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=flaskapp
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
  backend:
    build: flask-backend
    command: flask run --host=0.0.0.0
    # command: ./wait-for-it.sh db:3306 -- flask run --host=0.0.0.0
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - DB_USER=flaskapp
      - DB_PASS=${MYSQL_PASSWORD}
      - DB_NAME=flaskapp
      - DB_HOST=db
    depends_on:
      - db
  frontend:
    build:
      context: ./react-frontend
      dockerfile: Dockerfile.dev
    command: yarn start
    volumes:
      - ./react-frontend:/app
    ports:
      - "3000:3000"
    environment:
      - "REACT_APP_SERVER_URL=http://localhost:5000"
    depends_on:
      - backend
